[pytest]
#opciones por defecto al ejecutar 'pytest'
addopts=-v --tb=short --html=reportes/reporte.html --self-contained-html
#Patron de nombres para que pytest descubra los archivos y funciones de prueba
testpaths=tests
markers=
    login:pruebas relacionadas con el flujo de login
    smoke:pruebas criticas de humo
    regression:pruebas de regresion